In [1]:
import pandas as pd
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv("train_clean.csv")
test = pd.read_csv("test_clean.csv")
comb = pd.concat([test,train],axis=0)

comb.set_index('Id',inplace=True)

In [3]:
comb.corr()

,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,GarageArea,OverallQual,FullBath,GarageCars,TotRmsAbvGrd,SalePrice
YearBuilt,1.000000,0.612235,0.408558,0.310814,0.242666,0.481328,0.597554,0.471169,0.538611,0.114280,0.522897
YearRemodAdd,0.612235,1.000000,0.298161,0.242245,0.316972,0.375892,0.571532,0.457980,0.425033,0.198250,0.507101
TotalBsmtSF,0.408558,0.298161,1.000000,0.801672,0.445302,0.486010,0.549255,0.327820,0.437963,0.282191,0.613581
1stFlrSF,0.310814,0.242245,0.801672,1.000000,0.562538,0.491996,0.479152,0.373077,0.440552,0.391782,0.605852
GrLivArea,0.242666,0.316972,0.445302,0.562538,1.000000,0.484547,0.575126,0.630286,0.488933,0.808354,0.708624
GarageArea,0.481328,0.375892,0.486010,0.491996,0.484547,1.000000,0.565179,0.407520,0.889890,0.328628,0.623431
OverallQual,0.597554,0.571532,0.549255,0.479152,0.575126,0.565179,1.000000,0.528483,0.600743,0.389761,0.790982
FullBath,0.471169,0.457980,0.327820,0.373077,0.630286,0.407520,0.528483,1.000000,0.478876,0.527337,0.560664
GarageCars,0.538611,0.425033,0.437963,0.440552,0.488933,0.889890,0.600743,0.478876,1.000000,0.357947,0.640409
TotRmsAbvGrd,0.114280,0.198250,0.282191,0.391782,0.808354,0.328628,0.389761,0.527337,0.357947,1.000000,0.533723
SalePrice,0.522897,0.507101,0.613581,0.605852,0.708624,0.623431,0.790982,0.560664,0.640409,0.533723,1.000000

In [49]:
comb2 = pd.DataFrame()
for i in comb.columns:
    a = comb[i]
    if not i in ['YearBuilt','YearRemodAdd','TotalBsmtSF','1stFlrSF','GrLivArea','GarageArea','SalePrice']:
        a = pd.get_dummies(a)
    comb2 = pd.concat([comb2,a],axis=1)
comb2

,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,GarageArea,1,2,3,4,...,RM,ClyTile,CompShg,Membran,Metal,Roll,Tar&Grv,WdShake,WdShngl,SalePrice
1461,1961,1961,882.0,896,896,730.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,NaN
1462,1958,1958,1329.0,1329,1329,312.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,NaN
1463,1997,1998,928.0,928,1629,482.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,NaN
1464,1998,1998,926.0,926,1604,470.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,NaN
1465,1992,1992,1280.0,1280,1280,506.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1999,2000,953.0,953,1647,460.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,175000.0
1457,1978,1988,1542.0,2073,2073,500.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,210000.0
1458,1941,2006,1152.0,1188,2340,252.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,266500.0
1459,1950,1996,1078.0,1078,1078,240.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,142125.0
1460,1965,1965,1256.0,1256,1256,276.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,147500.0

In [61]:
comb = comb2.sort_index(ascending=True)

In [62]:
train = comb[comb['SalePrice'].notnull()]
test = comb[comb['SalePrice'].isnull()]

In [63]:
test.drop('SalePrice',inplace=True,axis=1)

C:\Users\samla\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [64]:
X = train.drop('SalePrice',axis=1)
y = train['SalePrice']

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

### Random Forest Regression

In [68]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=2, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [76]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(regr, X_train, y_train, cv=5)
scores.mean()

0.6245072744935325

In [77]:
regr.score(X_test,y_test)

0.6540374882866268